baseurl = "https://rayyildiz.com"
title = "Ramazan AYYILDIZ"

theme = "coder"

googleAnalytics ="UA-765318-11"
languagecode = "en"

paginate = 25
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "rayyildiz"
enableRobotsTXT = true

[taxonomies]
  series = "series"
  
[params]
    author = "Ramazan AYYILDIZ"
    description = "Ramazan AYYILDIZ"
    keywords = "blog,developer,personal,software engineer,java,golang,scala,cloud native,serverless"
    info = "Software Engineer"
    avatarurl = "avatars/rayyildiz.jpg"
    footercontent = "Just for fun"
    images = ["avatars/rayyildiz.jpg"]
    
    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/rayyildiz/rayyildiz.com/tree/"

    rtl = false

    disable_comments = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/rayyildiz"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/rayyildiz"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/rayyildiz"

[[params.social]]
    name = "Stackshare"
    icon = "fas fa-layer-group"
    weight = 4
    url = "https://stackshare.io/rayyildiz/stack"

[[params.social]]
    name = "Json"
    icon = "fas fa-hashtag"
    weight = 5
    url = "https://api.rayyildiz.com"

[languages]
    [languages.en]
        languagename = "English"
        title = "Ramazan AYYILDIZ"
        contentDir = "content/english"
        weight = 10

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Ramazan AYYILDIZ"
            info = "Software Engineer"
            description = "Ramazan AYYILDIZ's personal website"
            keywords = "blog,developer,personal"

        [languages.en.menu]
            #[[languages.en.menu.main]]
            #name = "Blog"
            #weight = 10
            #url = "/posts/"

            #[[languages.en.menu.main]]
            #name = "About"
            #weight = 20
            #url = "/about/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "/projects/"
            
            # [[languages.en.menu.main]]
            # name = "Contact me"
            # weight = 4
            # url = "/contact/"


    [languages.tr]
        languagename = "Turkce"
        title = "Ramazan AYYILDIZ"
        contentDir = "content/turkish"
        weight = 20

        [languages.tr.params]
            author = "Ramazan AYYILDIZ"
            description = "Ramazan AYYILDIZ'in kisiel websitesi"
            keywords = "blog,developer,kisisel"
            info = "Senior Software Architect"
            footercontent = "Bilgi paylasildikca buyur"
           # dateformat = "Jan 2, 2006"

        [languages.tr.menu]

            #[[languages.tr.menu.main]]
            #name = "Hakkimda"
            #weight = 20
            #url = "/tr/hakkimda/"

            [[languages.tr.menu.main]]
            name = "Java"
            weight = 1
            url = "/tr/tags/java/"

            [[languages.tr.menu.main]]
            name = "Yazilim Gelistirme"
            weight = 3
            url = "/tr/tags/software-development/"

            [[languages.tr.menu.main]]
            name = "Tum Yazilar"
            weight = 10
            url = "/tr/posts/"

            # [[languages.tr.menu.main]]
            # name = "Projeler"
            # weight = 3
            # url = "/tr/projeler/"
            
            # [[languages.tr.menu.main]]
            # name = "Iletisim"
            # weight = 4
            # url = "/tr/iletisim/"
